services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      ADMIN_TOKEN: EXAMPLE_ONLY_ADMIN_TOKEN_DO_NOT_USE
      SIGNUPS_ALLOWED: "true"
      WEBSOCKET_ENABLED: "true"
    volumes:
      - ./vw-data:/data
    ports:
      - "8080:80"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    volumes:
      - ./cloudflared:/etc/cloudflared
    restart: unless-stopped
